#version: "3.8"

services:
  product-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-api
    expose:
      - "80"
    restart: always

  nginx:
    image: nginx:latest
    container_name: product-api-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - product-api
    restart: always
